"""Build web/teas.js from a Shopify product export.

Usage: python3 web/tools/build_catalogue.py <products.json>
<products.json> is the search_products output (data.products.edges[].node with
variants and featuredMedia). Re-run whenever prices, stock or
tasting scores change; the page itself never calls Shopify.
"""
import json, re, sys
from pathlib import Path

WEB = Path(__file__).resolve().parents[1]

# Tasting scores mirror app/data/proposed-tea-profiles.ts (first draft, owner to verify).
TEAS = [
    # handle, display name, family, form, roast, umami, sweet, astringent, caffeine, notes
    ("dark-roast", "Hojicha Aka", "hojicha", "leaf", 9, 2, 7, 1, "low", "Deep and smoky, with vanilla and warm sweetness"),
    ("hojicha-kyo", "Hojicha Kyo", "hojicha", "leaf", 7, 3, 7, 1, "low", "Charcoal roasted. Sweet, smoky, never bitter"),
    ("hojicha-kaori", "Hojicha Powder Kaori", "hojicha", "powder", 8, 3, 6, 2, "low", "Rich and soothing, made for lattes and baking"),
    ("spring-hojicha", "Spring Hojicha", "hojicha", "leaf", 5, 5, 6, 2, "low", "May sencha, lightly roasted"),
    ("hoji-genmaicha", "Hoji-Genmaicha", "hojicha", "leaf", 7, 3, 7, 1, "low", "Hojicha Kyo with roasted mochi rice"),
    ("genmaicha", "Genmaicha Midori", "genmaicha", "leaf", 3, 4, 5, 4, "medium", "Green tea and toasted rice"),
    ("genmaicha-powder", "Genmaicha Powder Asa-Midori", "genmaicha", "powder", 3, 5, 6, 4, "medium", "Buttery, toasted sweetness"),
    ("kimidori-matcha", "Kimidori Matcha", "matcha", "powder", 0, 6, 4, 5, "high", "Our everyday Uji matcha"),
    ("takamidori-matcha-たかみどり", "Takamidori Matcha", "matcha", "powder", 0, 7, 5, 4, "high", "Vibrant and mellow, a gentle bite"),
    ("kitsune-matcha", "Kitsune Matcha", "matcha", "powder", 0, 9, 6, 2, "high", "First harvest, ceremonial grade"),
    ("kyoto-sencha", "Kyoto Sencha", "sencha", "leaf", 0, 5, 4, 6, "medium", "Bright first flush from a small Kyoto farm"),
    ("yame-sencha", "Yame Sencha", "sencha", "leaf", 1, 7, 5, 4, "medium", "Shaded, deep steamed, full and nutty"),
    ("oolong", "Miyazaki Oolong", "oolong", "leaf", 3, 3, 6, 3, "medium", "Organic, grown in Miyazaki, Kyushu"),
    ("japanese-oolong-needle-tea", "Oolong Needle Tea", "oolong", "leaf", 3, 3, 5, 3, "medium", "A rare Japanese oolong"),
]

def pick_variant(variants):
    """Smallest single pack. If that size is out, say so rather than upsell a 1kg bag."""
    singles = [v for v in variants if not re.search(r"\bx\s*\d|\+", v["title"])] or variants
    v = min(singles, key=lambda v: float(v["price"]))
    return v, (v["inventoryQuantity"] or 0) > 0


def main(src):
    nodes = {e["node"]["handle"]: e["node"] for e in json.load(open(src))["data"]["products"]["edges"]}
    out = []
    for handle, name, family, form, roast, umami, sweet, astr, caf, notes in TEAS:
        node = nodes[handle]
        variant, in_stock = pick_variant([e["node"] for e in node["variants"]["edges"]])
        slug = re.sub(r"[^a-z0-9-]+", "-", handle.encode("ascii", "ignore").decode()).strip("-")
        img_url = node["featuredMedia"]["preview"]["image"]["url"]
        img_url += ("&" if "?" in img_url else "?") + "width=480"  # Shopify CDN resize
        out.append({
            "id": slug, "handle": handle, "name": name, "family": family, "form": form,
            "roast": roast, "umami": umami, "sweetness": sweet, "astringency": astr,
            "caffeine": caf, "notes": notes,
            "size": variant["title"].split("/")[-1].strip(), "price": float(variant["price"]),
            "inStock": in_stock, "img": img_url,
            "url": f"https://hojichaya.com/products/{handle}?variant={variant['id'].split('/')[-1]}",
        })
    js = "// Generated by web/tools/build_catalogue.py. Do not edit by hand.\nwindow.HY_TEAS = " + json.dumps(out, ensure_ascii=False, indent=1) + ";\n"
    (WEB / "teas.js").write_text(js)
    print(f"{len(out)} teas; in stock: {sum(t['inStock'] for t in out)}")

if __name__ == "__main__":
    main(sys.argv[1])
